# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import report_pb2 as report__pb2


class ReportStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCovidDataForAllStates = channel.unary_stream(
                '/report.Report/GetCovidDataForAllStates',
                request_serializer=report__pb2.ReportRequest.SerializeToString,
                response_deserializer=report__pb2.StateCovidData.FromString,
                )


class ReportServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCovidDataForAllStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReportServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCovidDataForAllStates': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCovidDataForAllStates,
                    request_deserializer=report__pb2.ReportRequest.FromString,
                    response_serializer=report__pb2.StateCovidData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'report.Report', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Report(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCovidDataForAllStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/report.Report/GetCovidDataForAllStates',
            report__pb2.ReportRequest.SerializeToString,
            report__pb2.StateCovidData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
