# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: report.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='report.proto',
  package='report',
  syntax='proto3',
  serialized_options=b'Z\017./server/report',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0creport.proto\x12\x06report\"\x0f\n\rReportRequest\"\x93\x02\n\x0eStateCovidData\x12\r\n\x05state\x18\x01 \x01(\t\x12\x0f\n\x07updated\x18\x02 \x01(\x04\x12\r\n\x05\x63\x61ses\x18\x03 \x01(\x04\x12\x12\n\ntodayCases\x18\x04 \x01(\x04\x12\x0e\n\x06\x64\x65\x61ths\x18\x05 \x01(\x04\x12\x13\n\x0btodayDeaths\x18\x06 \x01(\x04\x12\x11\n\trecovered\x18\x07 \x01(\x04\x12\x0e\n\x06\x61\x63tive\x18\x08 \x01(\x04\x12\x1a\n\x12\x63\x61sesPerOneMillion\x18\t \x01(\x04\x12\x1b\n\x13\x64\x65\x61thsPerOneMillion\x18\n \x01(\x04\x12\r\n\x05tests\x18\x0b \x01(\x04\x12\x1a\n\x12testsPerOneMillion\x18\x0c \x01(\x04\x12\x12\n\npopulation\x18\r \x01(\x04\x32W\n\x06Report\x12M\n\x18GetCovidDataForAllStates\x12\x15.report.ReportRequest\x1a\x16.report.StateCovidData\"\x00\x30\x01\x42\x11Z\x0f./server/reportb\x06proto3'
)




_REPORTREQUEST = _descriptor.Descriptor(
  name='ReportRequest',
  full_name='report.ReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=39,
)


_STATECOVIDDATA = _descriptor.Descriptor(
  name='StateCovidData',
  full_name='report.StateCovidData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='report.StateCovidData.state', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated', full_name='report.StateCovidData.updated', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cases', full_name='report.StateCovidData.cases', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='todayCases', full_name='report.StateCovidData.todayCases', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deaths', full_name='report.StateCovidData.deaths', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='todayDeaths', full_name='report.StateCovidData.todayDeaths', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='recovered', full_name='report.StateCovidData.recovered', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='active', full_name='report.StateCovidData.active', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='casesPerOneMillion', full_name='report.StateCovidData.casesPerOneMillion', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deathsPerOneMillion', full_name='report.StateCovidData.deathsPerOneMillion', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tests', full_name='report.StateCovidData.tests', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='testsPerOneMillion', full_name='report.StateCovidData.testsPerOneMillion', index=11,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='population', full_name='report.StateCovidData.population', index=12,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=317,
)

DESCRIPTOR.message_types_by_name['ReportRequest'] = _REPORTREQUEST
DESCRIPTOR.message_types_by_name['StateCovidData'] = _STATECOVIDDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReportRequest = _reflection.GeneratedProtocolMessageType('ReportRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPORTREQUEST,
  '__module__' : 'report_pb2'
  # @@protoc_insertion_point(class_scope:report.ReportRequest)
  })
_sym_db.RegisterMessage(ReportRequest)

StateCovidData = _reflection.GeneratedProtocolMessageType('StateCovidData', (_message.Message,), {
  'DESCRIPTOR' : _STATECOVIDDATA,
  '__module__' : 'report_pb2'
  # @@protoc_insertion_point(class_scope:report.StateCovidData)
  })
_sym_db.RegisterMessage(StateCovidData)


DESCRIPTOR._options = None

_REPORT = _descriptor.ServiceDescriptor(
  name='Report',
  full_name='report.Report',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=319,
  serialized_end=406,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCovidDataForAllStates',
    full_name='report.Report.GetCovidDataForAllStates',
    index=0,
    containing_service=None,
    input_type=_REPORTREQUEST,
    output_type=_STATECOVIDDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPORT)

DESCRIPTOR.services_by_name['Report'] = _REPORT

# @@protoc_insertion_point(module_scope)
